version: '3'
services:
  dvwa:
    build: ./dvwa
    networks:
      proxynet:
        ipv4_address: 172.16.1.2
  https-proxy:
    build: ./web
    volumes:
      - ./web/httpd.conf:/usr/local/apache2/conf/httpd.conf
    ports:
      - 443:8443
    networks:
      proxynet:
        ipv4_address: 172.16.1.3
  modsec:
    build: ./modsec
    environment: 
      PROXY: 1
      BACKEND: 'http://172.16.1.2:80/'
       #PROXY_SSL: 1

      #volumes:
      #- ./modsec/testHTTPD.conf:/usr/local/apache2/conf/extra/httpd-modsecurity.conf
      #- ./modsec/modsecurity.conf:/etc/modsecurity.d/modsecurity.conf
    ports:
      - 8080:80
    networks:
      proxynet:
        ipv4_address: 172.16.1.4
networks:
  proxynet:
    ipam:
      config:
        - subnet: 172.16.1.0/24
